### ISSUE TITLE
Ticking Entity Server Crash

### ISSUE THREAD

**Issue by AetherBreaker** [mujmajnkraft/BetterSurvival#17]
The issue stated as fixed in the linked post below is either still not fixed in version 1.4.1, or was somehow broken again, as this exact same problem is happening to me here
Crash report:
https://pastebin.com/ejdU08ut

https://github.com/mujmajnkraft/BetterSurvival/issues/2

**Comment by Giggitybyte** [comment]
I don't believe this is directly related to #2.

A quick look at the crash log and a Google search leads me to believe that [the call to `Potion.isBeneficial()`](https://github.com/mujmajnkraft/BetterSurvival/blob/master/src/main/java/com/mujmajnkraft/bettersurvival/potions/PotionCleanse.java#L48) is the cause of this as I'm pretty sure that method is client sided method. And, since the crash report related to this issue came from a dedicated server, I'd say it's safe to assume that's why a `NoSuchMethodError` was thrown.

I could be completely off base here as this is just speculation based off of <10 minutes of research.

**Comment by Giggitybyte** [comment]
After forking this repo and playing around with it, I can confirm that the call to `Potion.isBeneficial()` is most definitely the cause. I'll be creating a PR that fixes this.
