### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by 123Kappa** [mujmajnkraft/BetterSurvival#7]
I am having this error spammed in console [com.mujmajnkraft.bettersurvival.eventhandlers.ModWeaponHandler:onEvent:184]: null

Which event is 184?

**Comment by TheFlash787** [comment]
It seems that the mod hasn't been updated on Git for over two years, aha. Therefore we can't see what :184 actually is. Welp.

**Comment by LinhyCZ** [comment]
I'm having the same issue.. Have you fixed it somehow? :)

**Comment by LemADEC** [comment]
It's a systematic print of the IWeaponEffect capability of attacker's sword.

**Comment by Qattos** [comment]
> It's a systematic print of the IWeaponEffect capability of attacker's sword.

Any way to fix it?
Should I throw away my sword and bow and not over enchant them next time?
My dragonbone bow and sword have like 6 enchantments on each one, my suspicion at some point was that the mod(or maybe the game) just couldn't handle all of those enchants or something.
BTW this issue is making my world unplayable because once it happens I become unable to interact with anything, everything stops moving, and I noticed that this AFAIK only happens when fighting a dragon.

**Comment by Qattos** [comment]
Update :
I removed a couple of BetterSurvival enchantments from my bow and the issue I described earlier stopped happening but I did get this on the console :
[com.mujmajnkraft.bettersurvival.eventhandlers.ModWeaponHandler:onEvent:184]: null

So I ended up removing BetterSurvival altogether which in reality didn't add much to my gameplay except for those tasty enchantments and so far everything is back to normal.
Hoping the mod's creator will bring it back to life some day.
