### ISSUE TITLE
Update the sourcecode

### ISSUE THREAD

**Issue by kristi71111** [mujmajnkraft/BetterSurvival#9]
While I understand that some people want to keep source code private but please for the love of god update the source code of this mod so that we don't have to use bytecode editors to get rid of loggers.

**Comment by TheFlash787** [comment]
+1 

This is a must-have with the recent popularity of RLCraft. There are currently a few major/minor issues with the code of the mod and we would love to help you out! We can tidy up the mod for you so that you can rest easy, without worrying whether the mod is working correctly or not. It gives the responsibility to the community to help improve this mod further, with bug fixes and new features.

If you could push your latest build to this repository, we would all love to help you out! ❤️

**Comment by Block-Vader** [comment]
I just updated the source code. However I messed up and it ended up in https://github.com/mujmajnkraft/BetterSurvival/tree/master/Desktop/Workspace/1.12. I will try to fix it.

**Comment by Kexerval** [comment]
@kristi71111 I believe this issue is now resolved. Would you mind closing? Thanks!
